
GET http://localhost:5000/Telemetry/Start
Accept: application/json

###
GET http://localhost:5000/Telemetry/Start?inMemory=true
Accept: application/json

###
GET http://localhost:5000/Telemetry/Stop
Accept: application/json

###
GET http://localhost:5000/Telemetry/GetTraceData
Accept: application/json

###
GET http://localhost:5000/Test/Hello?name=world&Schema=Contact
Accept: application/json

###
GET http://localhost:5000/Test/Hello?name=err&Schema=Contact
Accept: application/json

###
