scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
    
  - job_name: 'rmq-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['rmq:15692']
